### ISSUE TITLE
"Invalid purl " error when using the v3

### ISSUE THREAD

**Issue by rhamrouni-discovery** [nowsecure/nowsecure-sbom-action#8]
When using the `nowsecure-sbom-action` v3, we got an annotation error:

`Invalid purl: version must be percent-encoded`

It seems to be happening during converting NowSecure report to Snapshot format and uploading it to github.
ℹ️ Note that we don't have the error if we use the v2.

The full log:
```
Run nowsecure/nowsecure-sbom-action@v3
Run nowsecure/nowsecure-action/upload-app@v4
NowSecure assessment started. Report ID: b4a9d5f6-xxxxxxxxxxx
Run nowsecure/nowsecure-action/convert-sarif@v4
Processing report with ID: b4a9d5f6-xxxxxxxxxxx
No .nsconfig.yml found, ignoring
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Checking for NowSecure report...  b4a9d5f6-xxxxxxxxxxx
Converting NowSecure report to Snapshot format...
Error: Invalid purl: version must be percent-encoded
    at Function.fromString (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/node_modules/packageurl-js/src/package-url.js:195:1)
    at new c (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/node_modules/@github/dependency-submission-toolkit/dist/index.cjs:29:1)
Error: Invalid purl: version must be percent-encoded
    at convertToSnapshot (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/nowsecure-snapshot.ts:51:1)
    at /home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/utils/action-utils.ts:116:1
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/utils/action-utils.ts:36:1
    at new Promise (<anonymous>)
    at __webpack_modules__.5213.__awaiter (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/utils/action-utils.ts:32:1)
    at outputToDependencies (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/utils/action-utils.ts:112:1)
    at /home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/nowsecure-convert-sarif.ts:65:1
```

**Comment by rhamrouni-discovery** [comment]
hello @ksaunders and @cosdon 
we still have the same error, even after the fix 
```
Run nowsecure/nowsecure-sbom-action@v3
Run nowsecure/nowsecure-action/upload-app@v4
NowSecure assessment started. Report ID: f7853c5c-xxxxxxxx
Run nowsecure/nowsecure-action/convert-sarif@v4
Processing report with ID: f7853c5c-xxxxxxxx
No .nsconfig.yml found, ignoring
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Checking for NowSecure report...  f7853c5c-xxxxxxxx
Converting NowSecure report to Snapshot format...
Error: Invalid purl: version must be percent-encoded
    at Function.fromString (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/node_modules/packageurl-js/src/package-url.js:195:1)
    at new c (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/node_modules/@github/dependency-submission-toolkit/dist/index.cjs:29:1)
    at convertToSnapshot (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/nowsecure-snapshot.ts:51:1)
    at /home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/utils/action-utils.ts:116:1
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/utils/action-utils.ts:36:1
    at new Promise (<anonymous>)
    at __webpack_modules__.5213.__awaiter (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/utils/action-utils.ts:32:1)
    at outputToDependencies (/home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/utils/action-utils.ts:112:1)
    at /home/runner/work/_actions/nowsecure/nowsecure-action/v4/dist/src/nowsecure-convert-sarif.ts:65:1
Error: Invalid purl: version must be percent-encoded
```

**Comment by rhamrouni-discovery** [comment]
Any update on this @ksaunders @cosdon?
We still have the issue with v3 version

**Comment by ghost** [comment]
We have addressed the issue in a new patch release so it should begin working without any changes on your end. Thank you.
